In [1]:
import numpy as np

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
zeros_array = np.zeros((4, 6)) # массив из нулей
zeros_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
ones_array = np.ones(7) # одномерный массив из единиц
ones_array

array([1., 1., 1., 1., 1., 1., 1.])

In [7]:
range_array = np.arange(1, 10, 1) # массив с проходом с шагом 1
range_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
zeros_array.shape # форма массива

(4, 6)

In [9]:
zeros_array.dtype # тип данных в массиве

dtype('float64')

In [11]:
arr[0] # вывод элемента с индексом 0

np.int64(1)

In [12]:
arr[::-1] # вывод элементов в обратном порядке

array([6, 5, 4, 3, 2, 1])

In [13]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([9, 8, 7, 6])
sum12 = arr1 + arr2 # массивы можно: складывать 
sum12

array([10, 10, 10, 10])

In [14]:
dev12 = arr1 / arr2 # делить
dev12

array([0.11111111, 0.25      , 0.42857143, 0.66666667])

In [15]:
mean_val1 = arr1.mean() # находить среднее значение
mean_val1

np.float64(2.5)

In [16]:
const2 = arr2 * 4 # умножать на число
const2

array([36, 32, 28, 24])